### ISSUE TITLE
Hot key jarvis crash in Android by time???

### ISSUE THREAD

**Issue by dragonsongohan** [Kitt-AI/snowboy#437]
I use hot key Jarvis, the application is crash. I check, I change the time on Android machine before April 29, 2018, the application is still running normally. I corrected the time at 20 hours 10 on April 29 onwards, the application died.

**Comment by dragonsongohan** [comment]
Error Log: libc: 
Fatal signal 6 (SIGABRT), code -6 in tid 23755

**Comment by dodobardo** [comment]
I have the same problem on python, but on python I receive a message about an expired license... Maybe if can be helpful this is my open issue on google groups.

https://groups.google.com/a/kitt.ai/forum/#!topic/snowboy-discussion/uWrtW6W0TiM

**Comment by chenguoguo** [comment]
We'll fix it today.

**Comment by MaiTuanDat** [comment]
I have the same problem. Have you fixed it @chenguoguo ?

**Comment by dragonsongohan** [comment]
thank you very much! The problem has been fixed @chenguoguo

**Comment by chenguoguo** [comment]
Yes we have fixed the issue.

**Comment by gosailing** [comment]
Android sample using Jarvis.umdl crash, any other hot word will be fine.

Fatal signal 6 (SIGABRT), code -6 in tid 23963 (tt.snowboy.demo)

**Comment by pallaviMN** [comment]
@chenguohuo still observed crash

**Comment by pallaviMN** [comment]
@chenguoguo  , i am facing this issue in android & iOS, can you please give me the model that you have used. The one in the resources folder still crashes

**Comment by alvaromfcunha** [comment]
@chenguoguo Still got problems related with using the "jarvis.umdl" model in android. Other models work just fine.

Observed this on the logcat: 
`libc  F  16:02:36.626 |  Fatal signal 6 (SIGABRT), code -6 (SI_TKILL) in tid 27045 (mqt_native_modu), pid 26989 (smartmirror
                                                          _app)
                  DEBUG  F  16:02:36.811 |  #00 pc 00000000000220ac  /system/lib64/libc.so (abort+116)
                         F  16:02:36.811 |  #01 pc 00000000000ef664  /data/app/com.smartmirror_app-Mly3AOkMM1hb2oxJtsRbdw==/lib/arm64/libsnowbo
                                                          y-detect-android.so (__gnu_cxx::__verbose_terminate_handler()+348)
                         F  16:02:36.811 |  #02 pc 000000000009d2c0  /data/app/com.smartmirror_app-Mly3AOkMM1hb2oxJtsRbdw==/lib/arm64/libsnowbo
                                                          y-detect-android.so (__cxxabiv1::__terminate(void (*)())+8)
                         F  16:02:36.811 |  #03 pc 00000000000ee8c8  /data/app/com.smartmirror_app-Mly3AOkMM1hb2oxJtsRbdw==/lib/arm64/libsnowbo
                                                          y-detect-android.so
                         F  16:02:36.811 |  #04 pc 000000000009cd28  /data/app/com.smartmirror_app-Mly3AOkMM1hb2oxJtsRbdw==/lib/arm64/libsnowbo
                                                          y-detect-android.so (__gxx_personality_v0+156)
                         F  16:02:36.811 |  #05 pc 0000000000101320  /data/app/com.smartmirror_app-Mly3AOkMM1hb2oxJtsRbdw==/lib/arm64/libsnowbo
                                                          y-detect-android.so
                         F  16:02:36.811 |  #06 pc 0000000000101644  /data/app/com.smartmirror_app-Mly3AOkMM1hb2oxJtsRbdw==/lib/arm64/libsnowbo
                                                          y-detect-android.so (_Unwind_RaiseException+252)
                         F  16:02:36.811 |  #07 pc 000000000009d45c  /data/app/com.smartmirror_app-Mly3AOkMM1hb2oxJtsRbdw==/lib/arm64/libsnowbo
                                                          y-detect-android.so (__cxa_throw+124)
                         F  16:02:36.811 |  #08 pc 00000000000468a4  /data/app/com.smartmirror_app-Mly3AOkMM1hb2oxJtsRbdw==/lib/arm64/libsnowbo
                                                          y-detect-android.so (snowboy::SnowboyLogMsg::~SnowboyLogMsg()+776)
                         F  16:02:36.811 |  #09 pc 0000000000047d14  /data/app/com.smartmirror_app-Mly3AOkMM1hb2oxJtsRbdw==/lib/arm64/libsnowbo
                                                          y-detect-android.so (snowboy::ExpectToken(bool, char const*, std::istream*)+412)
                         F  16:02:36.811 |  #10 pc 0000000000068c10  /data/app/com.smartmirror_app-Mly3AOkMM1hb2oxJtsRbdw==/lib/arm64/libsnowbo
                                                          y-detect-android.so (snowboy::UniversalDetectStream::ReadHotwordModel(std::string con
                                                          st&)+1000)
                         F  16:02:36.811 |  #11 pc 0000000000069d5c  /data/app/com.smartmirror_app-Mly3AOkMM1hb2oxJtsRbdw==/lib/arm64/libsnowbo
                                                          y-detect-android.so (snowboy::UniversalDetectStream::UniversalDetectStream(snowboy::U
                                                          niversalDetectStreamOptions const&)+648)
                         F  16:02:36.811 |  #12 pc 000000000003ba14  /data/app/com.smartmirror_app-Mly3AOkMM1hb2oxJtsRbdw==/lib/arm64/libsnowbo
                                                          y-detect-android.so (snowboy::PipelineDetect::Init()+1224)
                         F  16:02:36.811 |  #13 pc 000000000002a3d8  /data/app/com.smartmirror_app-Mly3AOkMM1hb2oxJtsRbdw==/lib/arm64/libsnowbo
                                                          y-detect-android.so (snowboy::SnowboyDetect::SnowboyDetect(std::string const&, std::s
                                                          tring const&)+156)
                         F  16:02:36.811 |  #14 pc 00000000000270c0  /data/app/com.smartmirror_app-Mly3AOkMM1hb2oxJtsRbdw==/lib/arm64/libsnowbo
                                                          y-detect-android.so (Java_ai_kitt_snowboy_snowboyJNI_new_1SnowboyDetect+212)
                         F  16:02:36.811 |  #15 pc 000000000055e1e0  /system/lib64/libart.so (art_quick_generic_jni_trampoline+144)
                         F  16:02:36.812 |  #16 pc 000000000055544c  /system/lib64/libart.so (art_quick_invoke_static_stub+604)
                         F  16:02:36.812 |  #17 pc 00000000000cf714  /system/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int
                                                          *, unsigned int, art::JValue*, char const*)+232)
                         F  16:02:36.812 |  #18 pc 000000000027f2e0  /system/lib64/libart.so (art::interpreter::ArtInterpreterToCompiledCodeBri
                                                          dge(art::Thread*, art::ArtMethod*, art::ShadowFrame*, unsigned short, art::JValue*)+3
                                                          44)
                         F  16:02:36.812 |  #19 pc 00000000002792e8  /system/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::
                                                          ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short,
                                                           art::JValue*)+968)
                         F  16:02:36.812 |  #20 pc 0000000000525e1c  /system/lib64/libart.so (MterpInvokeStatic+204)
                         F  16:02:36.812 |  #21 pc 0000000000547a14  /system/lib64/libart.so (ExecuteMterpImpl+14612)
                         F  16:02:36.812 |  #22 pc 0000000000005ee0  <anonymous:00000070bbe11000> (ai.kitt.snowboy.SnowboyDetect.<init>)
                         F  16:02:36.812 |  #23 pc 0000000000252fec  /system/lib64/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20
                                                          CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEb.llvm.1260208031+488)
                         F  16:02:36.812 |  #24 pc 0000000000258ae0  /system/lib64/libart.so (art::interpreter::ArtInterpreterToInterpreterBrid
                                                          ge(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*, art::JValue*)+2
                                                          16)
                         F  16:02:36.812 |  #25 pc 00000000002792cc  /system/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::
                                                          ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short,
                                                           art::JValue*)+940)
                         F  16:02:36.812 |  #26 pc 0000000000525c58  /system/lib64/libart.so (MterpInvokeDirect+296)
                         F  16:02:36.812 |  #27 pc 0000000000547994  /system/lib64/libart.so (ExecuteMterpImpl+14484)
                         F  16:02:36.812 |  #28 pc 00000000000084ac  <anonymous:00000070bbe11000> (ai.kitt.snowboy.audio.RecordingThread.<init>
                                                          +112)
                         F  16:02:36.812 |  #29 pc 0000000000252fec  /system/lib64/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20
                                                          CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEb.llvm.1260208031+488)
                         F  16:02:36.812 |  #30 pc 0000000000258ae0  /system/lib64/libart.so (art::interpreter::ArtInterpreterToInterpreterBrid
                                                          ge(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*, art::JValue*)+2
                                                          16)
                         F  16:02:36.812 |  #31 pc 00000000002792cc  /system/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::
                                                          ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short,
                                                           art::JValue*)+940)
                         F  16:02:36.812 |  #32 pc 0000000000525c58  /system/lib64/libart.so (MterpInvokeDirect+296)
                         F  16:02:36.812 |  #33 pc 0000000000547994  /system/lib64/libart.so (ExecuteMterpImpl+14484)
                         F  16:02:36.812 |  #34 pc 00000000000036da  <anonymous:00000070bbe11000> (ai.kitt.snowboy.RNSnowBoyModule.initHotword+
                                                          74)
                         F  16:02:36.812 |  #35 pc 0000000000252fec  /system/lib64/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20
                                                          CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEb.llvm.1260208031+488)
                         F  16:02:36.812 |  #36 pc 00000000005151ac  /system/lib64/libart.so (artQuickToInterpreterBridge+1020)
                         F  16:02:36.812 |  #37 pc 000000000055e2fc  /system/lib64/libart.so (art_quick_to_interpreter_bridge+92)
                         F  16:02:36.812 |  #38 pc 0000000000555188  /system/lib64/libart.so (art_quick_invoke_stub+584)
                         F  16:02:36.812 |  #39 pc 00000000000cf6f4  /system/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int
                                                          *, unsigned int, art::JValue*, char const*)+200)
                         F  16:02:36.812 |  #40 pc 000000000045ca48  /system/lib64/libart.so (art::(anonymous namespace)::InvokeWithArgArray(ar
                                                          t::ScopedObjectAccessAlreadyRunnable const&, art::ArtMethod*, art::(anonymous namespa
                                                          ce)::ArgArray*, art::JValue*, char const*)+104)
                         F  16:02:36.812 |  #41 pc 000000000045e49c  /system/lib64/libart.so (art::InvokeMethod(art::ScopedObjectAccessAlreadyR
                                                          unnable const&, _jobject*, _jobject*, _jobject*, unsigned long)+1440)
                         F  16:02:36.812 |  #42 pc 00000000003ee3dc  /system/lib64/libart.so (art::Method_invoke(_JNIEnv*, _jobject*, _jobject*
                                                          , _jobjectArray*)+52)
                         F  16:02:36.812 |  #43 pc 000000000011e6d4  /system/framework/arm64/boot-core-oj.oat (offset 0x114000) (java.lang.Clas
                                                          s.getDeclaredMethodInternal [DEDUPED]+180)
                         F  16:02:36.812 |  #44 pc 0000000000555188  /system/lib64/libart.so (art_quick_invoke_stub+584)
                         F  16:02:36.812 |  #45 pc 00000000000cf6f4  /system/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int
                                                          *, unsigned int, art::JValue*, char const*)+200)
                         F  16:02:36.812 |  #46 pc 000000000027f2e0  /system/lib64/libart.so (art::interpreter::ArtInterpreterToCompiledCodeBri
                                                          dge(art::Thread*, art::ArtMethod*, art::ShadowFrame*, unsigned short, art::JValue*)+3
                                                          44)
                         F  16:02:36.812 |  #47 pc 00000000002792e8  /system/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::
                                                          ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short,
                                                           art::JValue*)+968)
                         F  16:02:36.812 |  #48 pc 0000000000524918  /system/lib64/libart.so (MterpInvokeVirtual+588)
                         F  16:02:36.812 |  #49 pc 0000000000547894  /system/lib64/libart.so (ExecuteMterpImpl+14228)
                         F  16:02:36.813 |  #50 pc 00000000002d1a10  <anonymous:0000007022d85000> (com.facebook.react.bridge.JavaMethodWrapper.
                                                          invoke+304)
                         F  16:02:36.813 |  #51 pc 0000000000252fec  /system/lib64/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20
                                                          CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEb.llvm.1260208031+488)
                         F  16:02:36.813 |  #52 pc 0000000000258ae0  /system/lib64/libart.so (art::interpreter::ArtInterpreterToInterpreterBrid
                                                          ge(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*, art::JValue*)+2
                                                          16)
                         F  16:02:36.813 |  #53 pc 00000000002792cc  /system/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::
                                                          ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short,
                                                           art::JValue*)+940)
                         F  16:02:36.813 |  #54 pc 0000000000525894  /system/lib64/libart.so (MterpInvokeInterface+1392)
                         F  16:02:36.813 |  #55 pc 0000000000547a94  /system/lib64/libart.so (ExecuteMterpImpl+14740)
                         F  16:02:36.813 |  #56 pc 00000000002d2032  <anonymous:0000007022d85000> (com.facebook.react.bridge.JavaModuleWrapper.
                                                          invoke+42)
                         F  16:02:36.813 |  #57 pc 0000000000252fec  /system/lib64/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20
                                                          CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEb.llvm.1260208031+488)
                         F  16:02:36.813 |  #58 pc 00000000005151ac  /system/lib64/libart.so (artQuickToInterpreterBridge+1020)
                         F  16:02:36.813 |  #59 pc 000000000055e2fc  /system/lib64/libart.so (art_quick_to_interpreter_bridge+92)
                         F  16:02:36.813 |  #60 pc 0000000000555188  /system/lib64/libart.so (art_quick_invoke_stub+584)
                         F  16:02:36.813 |  #61 pc 00000000000cf6f4  /system/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int
                                                          *, unsigned int, art::JValue*, char const*)+200)
                         F  16:02:36.813 |  #62 pc 000000000045ca48  /system/lib64/libart.so (art::(anonymous namespace)::InvokeWithArgArray(ar
                                                          t::ScopedObjectAccessAlreadyRunnable const&, art::ArtMethod*, art::(anonymous namespa
                                                          ce)::ArgArray*, art::JValue*, char const*)+104)
                         F  16:02:36.813 |  #63 pc 000000000045dddc  /system/lib64/libart.so (art::InvokeVirtualOrInterfaceWithVarArgs(art::Sco
                                                          pedObjectAccessAlreadyRunnable const&, _jobject*, _jmethodID*, std::__va_list)+440)
                         F  16:02:36.813 |  #64 pc 000000000033ef78  /system/lib64/libart.so (art::JNI::CallVoidMethodV(_JNIEnv*, _jobject*, _j
                                                          methodID*, std::__va_list)+656)
                         F  16:02:36.813 |  #65 pc 00000000000ffd88  /system/lib64/libart.so (art::(anonymous namespace)::CheckJNI::CallMethodV
                                                          (char const*, _JNIEnv*, _jobject*, _jclass*, _jmethodID*, std::__va_list, art::Primit
                                                          ive::Type, art::InvokeType)+2592)
                         F  16:02:36.813 |  #66 pc 00000000000ed18c  /system/lib64/libart.so (art::(anonymous namespace)::CheckJNI::CallVoidMet
                                                          hodV(_JNIEnv*, _jobject*, _jmethodID*, std::__va_list)+92)
                         F  16:02:36.813 |  #67 pc 00000000000156bc  /data/app/com.smartmirror_app-Mly3AOkMM1hb2oxJtsRbdw==/lib/arm64/libfb.so 
                                                          (_JNIEnv::CallVoidMethod(_jobject*, _jmethodID*, ...)+120)
                         F  16:02:36.813 |  #68 pc 00000000000753b8  /data/app/com.smartmirror_app-Mly3AOkMM1hb2oxJtsRbdw==/lib/arm64/libreactn
                                                          ativejni.so
                         F  16:02:36.813 |  #69 pc 000000000006b8bc  /data/app/com.smartmirror_app-Mly3AOkMM1hb2oxJtsRbdw==/lib/arm64/libreactn
                                                          ativejni.so
                         F  16:02:36.813 |  #70 pc 000000000005ac74  /data/app/com.smartmirror_app-Mly3AOkMM1hb2oxJtsRbdw==/lib/arm64/libreactn
                                                          ativejni.so (_ZN8facebook3jni6detail13MethodWrapperIMNS_5react15JNativeRunnableEFvvEX
                                                          adL_ZNS4_3runEvEES4_vJEE8dispatchENS0_9alias_refIPNS1_8JTypeForINS0_11HybridClassIS4_
                                                          NS3_8RunnableEE8JavaPartESB_vE11_javaobjectEEE+32)
                         F  16:02:36.813 |  #71 pc 000000000005abf0  /data/app/com.smartmirror_app-Mly3AOkMM1hb2oxJtsRbdw==/lib/arm64/libreactn
                                                          ativejni.so (_ZN8facebook3jni6detail15FunctionWrapperIPFvNS0_9alias_refIPNS1_8JTypeFo
                                                          rINS0_11HybridClassINS_5react15JNativeRunnableENS6_8RunnableEE8JavaPartES8_vE11_javao
                                                          bjectEEEEXadL_ZNS1_13MethodWrapperIMS7_FvvEXadL_ZNS7_3runEvEES7_vJEE8dispatchESE_EESD
                                                          _vJEE4callEP7_JNIEnvP8_jobject+56)
                         F  16:02:36.813 |  #72 pc 000000000055e1e0  /system/lib64/libart.so (art_quick_generic_jni_trampoline+144)
                         F  16:02:36.813 |  #73 pc 0000000000555188  /system/lib64/libart.so (art_quick_invoke_stub+584)
                         F  16:02:36.813 |  #74 pc 00000000000cf6f4  /system/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int
                                                          *, unsigned int, art::JValue*, char const*)+200)
                         F  16:02:36.813 |  #75 pc 000000000027f2e0  /system/lib64/libart.so (art::interpreter::ArtInterpreterToCompiledCodeBri
                                                          dge(art::Thread*, art::ArtMethod*, art::ShadowFrame*, unsigned short, art::JValue*)+3
                                                          44)
                         F  16:02:36.813 |  #76 pc 00000000002792e8  /system/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::
                                                          ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short,
                                                           art::JValue*)+968)
                         F  16:02:36.813 |  #77 pc 0000000000525894  /system/lib64/libart.so (MterpInvokeInterface+1392)
                         F  16:02:36.813 |  #78 pc 0000000000547a94  /system/lib64/libart.so (ExecuteMterpImpl+14740)
                         F  16:02:36.813 |  #79 pc 0000000000c60c76  /system/framework/boot-framework.vdex (android.os.Handler.handleCallback+4
                                                          )
                         F  16:02:36.813 |  #80 pc 0000000000252fec  /system/lib64/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20
                                                          CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEb.llvm.1260208031+488)
                         F  16:02:36.813 |  #81 pc 0000000000258ae0  /system/lib64/libart.so (art::interpreter::ArtInterpreterToInterpreterBrid
                                                          ge(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*, art::JValue*)+2
                                                          16)
                         F  16:02:36.813 |  #82 pc 00000000002792cc  /system/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::
                                                          ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short,
                                                           art::JValue*)+940)
                         F  16:02:36.813 |  #83 pc 0000000000525e1c  /system/lib64/libart.so (MterpInvokeStatic+204)
                         F  16:02:36.813 |  #84 pc 0000000000547a14  /system/lib64/libart.so (ExecuteMterpImpl+14612)
                         F  16:02:36.814 |  #85 pc 0000000000afb98c  /system/framework/boot-framework.vdex (android.os.Handler.dispatchMessage+
                                                          8)
                         F  16:02:36.814 |  #86 pc 0000000000252fec  /system/lib64/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20
                                                          CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEb.llvm.1260208031+488)
                         F  16:02:36.814 |  #87 pc 0000000000258ae0  /system/lib64/libart.so (art::interpreter::ArtInterpreterToInterpreterBrid
                                                          ge(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*, art::JValue*)+2
                                                          16)
                         F  16:02:36.814 |  #88 pc 00000000002792cc  /system/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::
                                                          ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short,
                                                           art::JValue*)+940)
                         F  16:02:36.814 |  #89 pc 0000000000524fb0  /system/lib64/libart.so (MterpInvokeSuper+1420)
                         F  16:02:36.814 |  #90 pc 0000000000547914  /system/lib64/libart.so (ExecuteMterpImpl+14356)
                         F  16:02:36.814 |  #91 pc 00000000002d7568  <anonymous:0000007022d85000> (com.facebook.react.bridge.queue.MessageQueue
                                                          ThreadHandler.dispatchMessage)
                         F  16:02:36.814 |  #92 pc 0000000000252fec  /system/lib64/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20
                                                          CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEb.llvm.1260208031+488)
                         F  16:02:36.814 |  #93 pc 0000000000258ae0  /system/lib64/libart.so (art::interpreter::ArtInterpreterToInterpreterBrid
                                                          ge(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*, art::JValue*)+2
                                                          16)
                         F  16:02:36.814 |  #94 pc 00000000002792cc  /system/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::
                                                          ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short,
                                                           art::JValue*)+940)
                         F  16:02:36.814 |  #95 pc 0000000000524918  /system/lib64/libart.so (MterpInvokeVirtual+588)
                         F  16:02:36.814 |  #96 pc 0000000000547894  /system/lib64/libart.so (ExecuteMterpImpl+14228)
                         F  16:02:36.814 |  #97 pc 0000000000b02abc  /system/framework/boot-framework.vdex (android.os.Looper.loop+404)
                         F  16:02:36.814 |  #98 pc 0000000000252fec  /system/lib64/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20
                                                          CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEb.llvm.1260208031+488)
                         F  16:02:36.814 |  #99 pc 0000000000258ae0  /system/lib64/libart.so (art::interpreter::ArtInterpreterToInterpreterBrid
                                                          ge(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*, art::JValue*)+2
                                                          16)
                         F  16:02:36.814 |  #100 pc 00000000002792cc  /system/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art:
                                                          :ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short
                                                          , art::JValue*)+940)
                         F  16:02:36.814 |  #101 pc 0000000000525e1c  /system/lib64/libart.so (MterpInvokeStatic+204)
                         F  16:02:36.814 |  #102 pc 0000000000547a14  /system/lib64/libart.so (ExecuteMterpImpl+14612)
                         F  16:02:36.814 |  #103 pc 00000000002d76f6  <anonymous:0000007022d85000> (com.facebook.react.bridge.queue.MessageQueu
                                                          eThreadImpl$4.run+74)
                         F  16:02:36.814 |  #104 pc 0000000000252fec  /system/lib64/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_2
                                                          0CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEb.llvm.1260208031+488)
                         F  16:02:36.814 |  #105 pc 0000000000258ae0  /system/lib64/libart.so (art::interpreter::ArtInterpreterToInterpreterBri
                                                          dge(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*, art::JValue*)+
                                                          216)
                         F  16:02:36.814 |  #106 pc 00000000002792cc  /system/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art:
                                                          :ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short
                                                          , art::JValue*)+940)
                         F  16:02:36.814 |  #107 pc 0000000000525894  /system/lib64/libart.so (MterpInvokeInterface+1392)
                         F  16:02:36.814 |  #108 pc 0000000000547a94  /system/lib64/libart.so (ExecuteMterpImpl+14740)
                         F  16:02:36.814 |  #109 pc 00000000000ca876  /system/framework/boot-core-oj.vdex (java.lang.Thread.run+12)
                         F  16:02:36.814 |  #110 pc 0000000000252fec  /system/lib64/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_2
                                                          0CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEb.llvm.1260208031+488)
                         F  16:02:36.814 |  #111 pc 00000000005151ac  /system/lib64/libart.so (artQuickToInterpreterBridge+1020)
                         F  16:02:36.814 |  #112 pc 000000000055e2fc  /system/lib64/libart.so (art_quick_to_interpreter_bridge+92)
                         F  16:02:36.814 |  #113 pc 0000000000555188  /system/lib64/libart.so (art_quick_invoke_stub+584)
                         F  16:02:36.814 |  #114 pc 00000000000cf6f4  /system/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned in
                                                          t*, unsigned int, art::JValue*, char const*)+200)
                         F  16:02:36.814 |  #115 pc 000000000045ca48  /system/lib64/libart.so (art::(anonymous namespace)::InvokeWithArgArray(a
                                                          rt::ScopedObjectAccessAlreadyRunnable const&, art::ArtMethod*, art::(anonymous namesp
                                                          ace)::ArgArray*, art::JValue*, char const*)+104)
                         F  16:02:36.814 |  #116 pc 000000000045db04  /system/lib64/libart.so (art::InvokeVirtualOrInterfaceWithJValues(art::Sc
                                                          opedObjectAccessAlreadyRunnable const&, _jobject*, _jmethodID*, jvalue*)+424)
                         F  16:02:36.814 |  #117 pc 00000000004889a0  /system/lib64/libart.so (art::Thread::CreateCallback(void*)+1120)
                         F  16:02:36.814 |  #118 pc 0000000000092028  /system/lib64/libc.so (__pthread_start(void*)+36)
                         F  16:02:36.814 |  #119 pc 0000000000023968  /system/lib64/libc.so (__start_thread+68)`

Environment: 
- Processor: Qualcomm Snapdragon 450;
- Android Pie 9.0 w/ kernel version 3.18.120-perf-g49686bc.
