### ISSUE TITLE
Alsa problems on RaspBerry Pi3

### ISSUE THREAD

**Issue by adimnno** [Kitt-AI/snowboy#45]
I'm using Raspberry Pi3 with raspbian for implementation.
When running the python demo, comes the error messages as follow: 

```
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.front.0:CARD=0'
ALSA lib conf.c:4259:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4738:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM front
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.surround51.0:CARD=0'
ALSA lib conf.c:4259:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4738:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM surround21
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.surround51.0:CARD=0'
ALSA lib conf.c:4259:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4738:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM surround21
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.surround40.0:CARD=0'
ALSA lib conf.c:4259:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4738:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM surround40
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.surround51.0:CARD=0'
ALSA lib conf.c:4259:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4738:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM surround41
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.surround51.0:CARD=0'
ALSA lib conf.c:4259:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4738:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM surround50
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.surround51.0:CARD=0'
ALSA lib conf.c:4259:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4738:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM surround51
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.surround71.0:CARD=0'
ALSA lib conf.c:4259:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4738:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM surround71
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.iec958.0:CARD=0,AES0=4,AES1=130,AES2=0,AES3=2'
ALSA lib conf.c:4259:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4738:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM iec958
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.iec958.0:CARD=0,AES0=4,AES1=130,AES2=0,AES3=2'
ALSA lib conf.c:4259:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4738:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM spdif
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.iec958.0:CARD=0,AES0=4,AES1=130,AES2=0,AES3=2'
ALSA lib conf.c:4259:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4738:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM spdif
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib pulse.c:243:(pulse_connect) PulseAudio: Unable to connect: Connection refused

ALSA lib pulse.c:243:(pulse_connect) PulseAudio: Unable to connect: Connection refused

Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
Listening. . . Press Ctrl + C to exit
```

I have followed the instructions on https://snowboy.kitt.ai/docs to modify the .asoundrc file. I am not able to figure out the problems here. Is it something about alsa configuration or the port audio settings?

**Comment by chenguoguo** [comment]
Is the detection actually working? Sometimes you see errors/warnings like this but the detection is already working. Also, see the thread here https://github.com/Kitt-AI/snowboy/issues/9, people are able to get rid of those errors/warnings.

**Comment by Kushcabbage** [comment]
I have the same errors as above and it isnt working. Does a server socket need to be installed?

**Comment by chenguoguo** [comment]
@Kushcabbage it's most likely the audio configuration problem.
1. Please make sure you follow https://snowboy.kitt.ai/docs to set up the audio configuration.
2. Make sure you are able to record using `rec test.wav`, and make sure the recorded audio sounds good to you.
2. When you say it's not working, did you mean the universal we provide in the example was not working? Or did you mean you trained the personal model on the website, it worked on the website but didn't work for you when you use it in the example? Sometimes if the audio is not set up correct (e.g., microphone mismatch, too low input volume), it may lead to bad performance and may give you the feeling that it's not working.
4. this might be helpful (I doubt it though...): https://ubuntuforums.org/showthread.php?t=1905773

**Comment by Kushcabbage** [comment]
I followed the steps in the docs and both the record and playback works flawlessly. I was able to fix the server socket error but running `jack_control start` before running the demo (I feel like this should be added to the docs). Now I have an error from pyaudio saying sample rate is invalid. I understand the Snowboy requires data in a 16000 Hz sample rate, however my mic is 44100Hz, is this the issue? On a side note I am able to use `arecord -r 16000 t.wav` to record a 16000 Hz file

**Comment by chenguoguo** [comment]
There could be two possibilities:
1. Your microphone does not support 16000 sample rate. It was PyAudio that wasn't able to capture the audio from sound card. You could take a look at for example: http://stackoverflow.com/questions/4623572/how-do-i-get-a-list-of-my-devices-audio-sample-rates-using-pyaudio-or-portaudio
2. It's more likely that your audio configuration was messed up. Was this a fresh installation? Sometimes people have this problem on Raspberry Pis, and they are able to fix the problem by re-install the image from scratch.

**Comment by chenguoguo** [comment]
There could be two possibilities:
1. Your microphone does not support 16000 sample rate. It was PyAudio that wasn't able to capture the audio from sound card. You could take a look at for example: http://stackoverflow.com/questions/4623572/how-do-i-get-a-list-of-my-devices-audio-sample-rates-using-pyaudio-or-portaudio
2. It's more likely that your audio configuration was messed up. Was this a fresh installation? Sometimes people have this problem on Raspberry Pis, and they are able to fix the problem by re-install the image from scratch.

**Comment by chenguoguo** [comment]
There could be two possibilities:
1. Your microphone does not support 16000 sample rate. It was PyAudio that wasn't able to capture the audio from sound card. You could take a look at for example: http://stackoverflow.com/questions/4623572/how-do-i-get-a-list-of-my-devices-audio-sample-rates-using-pyaudio-or-portaudio
2. It's more likely that your audio configuration was messed up. Was this a fresh installation? Sometimes people have this problem on Raspberry Pis, and they are able to fix the problem by re-install the image from scratch.

**Comment by chenguoguo** [comment]
There could be two possibilities:
1. Your microphone does not support 16000 sample rate. It was PyAudio that wasn't able to capture the audio from sound card. You could take a look at for example: http://stackoverflow.com/questions/4623572/how-do-i-get-a-list-of-my-devices-audio-sample-rates-using-pyaudio-or-portaudio
2. It's more likely that your audio configuration was messed up. Was this a fresh installation? Sometimes people have this problem on Raspberry Pis, and they are able to fix the problem by re-install the image from scratch.

**Comment by chenguoguo** [comment]
There could be two possibilities:
1. Your microphone does not support 16000 sample rate. It was PyAudio that wasn't able to capture the audio from sound card. You could take a look at for example: http://stackoverflow.com/questions/4623572/how-do-i-get-a-list-of-my-devices-audio-sample-rates-using-pyaudio-or-portaudio
2. It's more likely that your audio configuration was messed up. Was this a fresh installation? Sometimes people have this problem on Raspberry Pis, and they are able to fix the problem by re-install the image from scratch.

**Comment by Kushcabbage** [comment]
This is the output for my usb soundcard from Pyaudio's system_info.py
> 	defaultSampleRate: 44100.0
	defaultLowOutputLatency: 0.00868480725624
	defaultLowInputLatency: 0.00868480725624
	maxInputChannels: 1
	structVersion: 2
	hostApi: 0 (ALSA)
	index: 2
	defaultHighOutputLatency: 0.0348299319728
	maxOutputChannels: 2
	name: USB Audio Device: - (hw:1,0)
	defaultHighInputLatency: 0.0348299319728
	Input rates: [44100.0, 48000.0]
	Output rates: [44100.0, 48000.0]
	Full duplex: [44100.0, 48000.0]

So I suppose the mic/card just doesn't support 16000?
Also yes this is a fresh install of raspbian

**Comment by chenguoguo** [comment]
Most likely. I guess we'll have to replace PyAudio with something else as ALSA is causing a lot of problems. In the meantime you could probably try to use some other microphones?

**Comment by Kushcabbage** [comment]
Yeah I may actually have a PS3 camera lying around somewhere.. So is this the fault of my microphone or the usb soundcard?

**Comment by chenguoguo** [comment]
Did you use any external usb sound card? Raspberry Pi doesn't come with usb sound card. If you use PS3 camera then you should be fine since that things has usb sound card, and we've verified that it's working on our end.

**Comment by Kushcabbage** [comment]
Yeah I'm using an external usb sound card with a microphone and speakers connected to the 3.5mm jacks. I suppose a usb mic is recommended?

**Comment by chenguoguo** [comment]
Yes, it will work better with USB microphones.

**Comment by Kushcabbage** [comment]
I now have the playstation camera setup as default by using .asoundrc , but it still throws the Invalid sample rate error

> `sudo python demo.py FRIDAY.pmdl`
> ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM dsnoop:1
> ALSA lib pcm_dmix.c:1022:(snd_pcm_dmix_open) unable to open slave
> ALSA lib pcm_dmix.c:1022:(snd_pcm_dmix_open) unable to open slave
> ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
> ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
> ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
> ALSA lib pulse.c:243:(pulse_connect) PulseAudio: Unable to connect: Connection refused
> 
> ALSA lib pulse.c:243:(pulse_connect) PulseAudio: Unable to connect: Connection refused
> 
> ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM dsnoop:1
> ALSA lib pcm_dmix.c:1022:(snd_pcm_dmix_open) unable to open slave
> ALSA lib pcm_dmix.c:1022:(snd_pcm_dmix_open) unable to open slave
> Expression 'paInvalidSampleRate' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 2048
> Expression 'PaAlsaStreamComponent_InitialConfigure( &self->capture, inParams, self->primeBuffers, hwParamsCapture, &realSr )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 2719
> Expression 'PaAlsaStream_Configure( stream, inputParameters, outputParameters, sampleRate, framesPerBuffer, &inputLatency, &outputLatency, &hostBufferSizeMode )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 2843
> Traceback (most recent call last):
>   File "demo.py", line 27, in <module>
>     detector = snowboydecoder.HotwordDetector(model, sensitivity=0.5)
>   File "/home/pi/Desktop/FRIDAY/Snowboy/rpi-arm-raspbian-8.0-1.0.4/snowboydecoder.py", line 119, in __init__
>     stream_callback=audio_callback)
>   File "build/bdist.linux-armv7l/egg/pyaudio.py", line 750, in open
>     
>   File "build/bdist.linux-armv7l/egg/pyaudio.py", line 441, in __init__
>     # calling pa.open returns a stream object
> IOError: [Errno -9997] Invalid sample rate

**Comment by Kushcabbage** [comment]
Ok the error above originates from where the output stream is opened, I was able to fix this by specifying the device index number. If the device index option is set before the rate then `rate=self.detector.SampleRate()` can be used to set the rate correctly. Then the same invalid sample rate error occured for me on the output stream as my sound card is 44100 and the ding.wav is 16000, I fixed this by hardcoding the output stream rate as 44100 and also specifying the device index.

To find pyaudio device indexes I made a py file with this inside:
```
import pyaudio
p = pyaudio.PyAudio()
for i in range(p.get_device_count()):
  dev = p.get_device_info_by_index(i)
  print((i,dev['name'],dev['maxInputChannels']))
```

**Comment by chenguoguo** [comment]
@Kushcabbage thanks for letting us know. This is very wired, if we have already set up the .asoundrc file, PyAudio should have picked up the right device. Anyways I'll keep this in mind when people ask in the future. Closing this since problem has been solved. Thanks!

**Comment by adimnno** [comment]
Thank you so much @Kushcabbage  and @chenguoguo ! 
After hardcoding the sample rate and the input output device to pyaudio, the errors are gone yet ALSA warnings still exist. It seems that the mic works but the detection never succeeds. I found that the `ans=self.detector.RunDetection(data)` in _snowboydecoder.py_ always returns a -2 when nothing happens and a 0 when whatever I speak to mic. It never returns number > 0.
I am not sure if it is the data collected by the mic or other part may go wrong. At least it did detect the input from the mic when it changes to 0 I think. 
I am using the file resources/snowboy.umdl from this git as the model.

**Comment by chenguoguo** [comment]
It could be that the input audio was not good enough. You could play with the sensitivity or audio_gain in this file (assuming you are using the Python example): https://github.com/Kitt-AI/snowboy/blob/master/examples/Python/snowboydecoder.py

Increasing the sensitivity will make the detection easy, but will also introduce false alarms, it's a value between 0 and 1. Increasing the audio_gain will boost the input audio amplitude, you could try a value between 1 and 10.

**Comment by adimnno** [comment]
- Using snowboy.umdl, I tried different pairs of sensitivity and audio_gain, none of them can make a success of detection, there is not even a false alarm.
- Then I recorded three audio of my saying "Alexa" using the same system of the raspberry. I trained another Alexa.pmdl using those sound files.
- On my mac, I also build the snowboy and tried it with the snowboy.umdl. It doesn't work either.
- On mac, I tried with my own trained Alexa.pmdl. It works well.
- When I try Alexa.pmdl in raspberry Pi with different pairs of sensitivity and audio_gain, unfortunately only when I make the sensitivity above 0.8 that the detection always gave false alarms. Never detect the actual saying of "alexa" I think.
- I doubt it is the pyaudio input stream that does not have a right data in then.

**Comment by chenguoguo** [comment]
@adimnno when you record the Alexa samples on Raspberry Pi, and then upload it to snowboy.kitt.ai for model training, could you make sure that those audio samples are in good shape? In particular, please cut off the surrounding audio around Alexa for each audio sample. Sometime microphones on Raspberry Pi has noise and the VAD does not work well on that. Most likely that will make your Alexa.pmdl model work on Rapsberry Pi (assuming you use the same microphone).

**Comment by adimnno** [comment]
I have modified a little of the snowboydecoder.py to let it detect the data from my recorded sample files rather than the data from the microphone. I am using the Alexa.pmdl generated from your website by my voice samples.
When I use **arecord** command to record "alexa" samples like this: 
`arecord -r16000 -c1 -twav -fS16_LE -Dplughw:1,0 test16k.wav`
It is OK that I set the samplerate to 16k 48k or 96k for the recording samples. Only the 16k sample is detected.
When I use **rec** command to record "alexa" samples, even if I put "-r16000" variable, a warning will be shown and the samplerate is forced to be reset to 48000 then. So I can only record the 48k sample and it was never detected then. (The warning is:`rec WARN formats: can't set sample rate 16000; using 48000`)
According to all above, only the 16k sample can be detected. But as it was said that in snowboydecoder.py, I have to set the sample rate to 48000 to avoid errors. Is it the problems with sox and pyaudio that can't change the sample rate to 16000 then?

By the way, Happy Mid-Autumn Festival!

**Comment by chenguoguo** [comment]
Yes the sample rate has to be 16000 for Snowboy to work. It's probably a ALSA configuration problem. Have you set up your .asoundrc file correct? Have you tried @Kushcabbage 's trick (see above) to specify the microphone that supports 16000 sample rate?

And thanks for mentioning the Mid-Autumn Festival, I miss my moon cakes :-)

**Comment by adimnno** [comment]
My USB microphone has a default sample rate of 48000. I just changed your input_stream's parameters to 48000 which avoided the errors but never work with the recognition.  I think I will either change to another mic or convert the input sound from 48000 to 16000 programmatically then. It seems that command arecord can convert input to assigned sample rate automatically as I used the same USB microphone to record my samples.

**Comment by artie88** [comment]
I fixed the problem. 
The problem came from USB microphone setting and the Audio output mode of Raspberry.
1. Microphone setting
follow this link http://docs.kitt.ai/snowboy/#running-on-pi
and test the recording functionality by this command 
rec temp.wav

If it doesn't work follow the instruction at the link above.
if it works, then test it by this command
play temp.wav

2. Audio output setting
If you can't hear the sound you recorded then try the following command.

amixer cset numid=3 1

1: 3.5 audio jack
2: HDMI output

Initially, it is 0 (automatic) but it doesn't work for some reason.

Hope it works!

**Comment by pojda** [comment]
I can record and play (using rec/play provided by sox) just fine, but when I instantiate PyAudio() I always get the same error. *sigh*

I'm still looking for answers and I'll post as soon as I find any.

>>> import pyaudio
>>> p = pyaudio.PyAudio()
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.front.0:CARD=0'
ALSA lib conf.c:4259:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4738:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM front
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.surround51.0:CARD=0'
ALSA lib conf.c:4259:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4738:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM surround21
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.surround51.0:CARD=0'
ALSA lib conf.c:4259:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4738:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM surround21
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.surround40.0:CARD=0'
ALSA lib conf.c:4259:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4738:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM surround40
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.surround51.0:CARD=0'
ALSA lib conf.c:4259:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4738:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM surround41
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.surround51.0:CARD=0'
ALSA lib conf.c:4259:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4738:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM surround50
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.surround51.0:CARD=0'
ALSA lib conf.c:4259:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4738:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM surround51
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.surround71.0:CARD=0'
ALSA lib conf.c:4259:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4738:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM surround71
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.iec958.0:CARD=0,AES0=4,AES1=130,AES2=0,AES3=2'
ALSA lib conf.c:4259:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4738:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM iec958
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.iec958.0:CARD=0,AES0=4,AES1=130,AES2=0,AES3=2'
ALSA lib conf.c:4259:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4738:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM spdif
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.iec958.0:CARD=0,AES0=4,AES1=130,AES2=0,AES3=2'
ALSA lib conf.c:4259:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4738:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM spdif
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline

**Comment by chenguoguo** [comment]
In most cases Snowboy still works even with though warnings/errors.

We also have an arecord demo, so if you can't make PyAudio work, please give it a try: https://github.com/Kitt-AI/snowboy/blob/master/examples/Python/demo_arecord.py

**Comment by manyxu** [comment]
I find the problem that some usb microphone does not support rate 16000, 1 channel. If there comes some converting code, will be great!
